name: agenticode
region: nyc
services:
  - name: webhook-server
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: ${GITHUB_REPO}
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    envs:
      - key: GITHUB_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: CODE_AGENT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: REVIEWER_AGENT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_REPOSITORY
        scope: RUN_TIME
        type: GENERAL
      - key: LLM_PROVIDER
        scope: RUN_TIME
        value: "openai"
      - key: LLM_MODEL
        scope: RUN_TIME
        value: "gpt-4o-mini"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MAX_ITERATIONS
        scope: RUN_TIME
        value: "5"
      - key: MAX_REVIEW_ROUNDS
        scope: RUN_TIME
        value: "3"
      - key: WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
